[Main]
Title=Symantec Ghost
Type=script
Selected=True
Level=5
Author=Raetha
Credits=http://www.symantec.com/business/ghost-solution-suite
Description=(Tested with v8.0.0.984) Symantec Ghost - Utiltity to create and restore hard drive images.#$X#$XScript does not include program files due to potential licensing conflicts.
Download_Level=2
Version=2
Date=15 Apr 2010

[Variables]
%ProgramFolder%=Ghost
%ProgramEXE%=Ghost32.exe
%ProgramTitle%=Ghost

[Process]
Echo,"Processing %ProgramTitle%..."
RunFromRam,%pCheckBox1%
DirCopy,"%ScriptDir%\%ProgramFolder%\*.*","%target_prog%\%ProgramFolder%"
CopyOrExpand,"%source_win%\snmpapi.dll","%target_sys%"
If,%pCheckBox2%,Equal,True,Add_Shortcut,Desktop
If,%pCheckBox3%,Equal,True,Add_Shortcut,QuickLaunch
If,%pCheckBox4%,Equal,True,Add_Shortcut,StartMenu,%pTextBox1%

[Interface]
pCheckBox1="Run from RAM (boot.wim or RAMdisk)",1,3,10,11,200,18,False
pCheckBox2="Add Desktop shortcut(s)",1,3,11,41,200,18,True
pCheckBox3="Add Quick Launch shortcut(s)",1,3,11,64,200,18,False
pCheckBox4="Add Start Menu shortcut(s)",1,3,11,87,200,18,True
pTextBox1="Start Menu folder:",1,0,11,126,200,18,
pBevel1=pBevel1,1,12,6,36,210,115
pWebLabel1="Symantec Ghost Website",1,10,221,11,200,18,http://www.symantec.com/business/ghost-solution-suite
pTextFile1=Ghost_Setup.txt,1,6,221,36,325,270

[InterfaceEncoded]
Ghost_Setup.txt=209,279

[EncodedFile-InterfaceEncoded-Ghost_Setup.txt]
lines=0
0=eJxNjTEOwjAQBHtL/sMqDR0FNIgP8AD4gBUuyUlnX5Q7K+T3OKGhXI1m9qWoRvCJDdYvPDs2rcjVHLPOVZITErrHpOYdBpU3LVi5CeWwYvhpJ/uHDdG+RVcuIwaWNhfNLSXaJ8Fzy6k49TjCMdzAxTxJ+2Mt9xhiGHdyvZzpQ196uzp7eJzjd8/ILy6JD04tKS3QK6koYRgFIwosg9ItOOStWcwWMDABAAjoCFSIZRspAQAAAAIAAAApAAAAhAAAAAAAAAABAAAAAAAAAAAAAAA

